TRUNCATE TABLE currencies;

INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Leke', 'ALL', 'Lek');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'USD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Afghanis', 'AFN', '؋');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'ARS', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Guilders', 'AWG', 'ƒ');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'AUD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('New Manats', 'AZN', 'ман');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'BSD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'BBD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rubles', 'BYR', 'p.');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Euro', 'EUR', '€');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'BZD', 'BZ$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'BMD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Bolivianos', 'BOB', '$b');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Convertible Marka', 'BAM', 'KM');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pula', 'BWP', 'P');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Leva', 'BGN', 'лв');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Reais', 'BRL', 'R$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'GBP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'BND', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Riels', 'KHR', '៛');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'CAD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'KYD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'CLP', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Yuan Renminbi', 'CNY', '¥');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'COP', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Colón', 'CRC', '₡');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Kuna', 'HRK', 'kn');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'CUP', '₱');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Koruny', 'CZK', 'Kč');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Kroner', 'DKK', 'kr');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'DOP ', 'RD$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'XCD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'EGP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Colones', 'SVC', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'FKP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'FJD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Cedis', 'GHC', '¢');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'GIP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Quetzales', 'GTQ', 'Q');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'GGP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'GYD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Lempiras', 'HNL', 'L');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'HKD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Forint', 'HUF', 'Ft');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Kronur', 'ISK', 'kr');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupees', 'INR', 'Rp');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupiahs', 'IDR', 'Rp');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rials', 'IRR', '﷼');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'IMP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('New Shekels', 'ILS', '₪');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'JMD', 'J$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Yen', 'JPY', '¥');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'JEP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Tenge', 'KZT', 'лв');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Won', 'KPW', '₩');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Won', 'KRW', '₩');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Soms', 'KGS', 'лв');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Kips', 'LAK', '₭');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Lati', 'LVL', 'Ls');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'LBP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'LRD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Switzerland Francs', 'CHF', 'CHF');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Litai', 'LTL', 'Lt');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Denars', 'MKD', 'ден');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Ringgits', 'MYR', 'RM');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupees', 'MUR', '₨');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'MXN', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Tugriks', 'MNT', '₮');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Meticais', 'MZN', 'MT');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'NAD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupees', 'NPR', '₨');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Guilders', 'ANG', 'ƒ');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'NZD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Cordobas', 'NIO', 'C$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Nairas', 'NGN', '₦');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Krone', 'NOK', 'kr');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rials', 'OMR', '﷼');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupees', 'PKR', '₨');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Balboa', 'PAB', 'B/.');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Guarani', 'PYG', 'Gs');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Nuevos Soles', 'PEN', 'S/.');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'PHP', 'Php');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Zlotych', 'PLN', 'zł');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rials', 'QAR', '﷼');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('New Lei', 'RON', 'lei');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rubles', 'RUB', 'руб');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'SHP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Riyals', 'SAR', '﷼');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dinars', 'RSD', 'Дин.');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupees', 'SCR', '₨');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'SGD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'SBD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Shillings', 'SOS', 'S');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rand', 'ZAR', 'R');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupees', 'LKR', '₨');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Kronor', 'SEK', 'kr');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'SRD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pounds', 'SYP', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('New Dollars', 'TWD', 'NT$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Baht', 'THB', '฿');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'TTD', 'TT$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Lira', 'TRY', '₺');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Liras', 'TRL', '£');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dollars', 'TVD', '$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Hryvnia', 'UAH', '₴');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Pesos', 'UYU', '$U');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Sums', 'UZS', 'лв');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Bolivares Fuertes', 'VEF', 'Bs');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Dong', 'VND', '₫');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rials', 'YER', '﷼');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Zimbabwe Dollars', 'ZWD', 'Z$');
INSERT INTO Currencies (Name, Code, Symbol) VALUES ('Rupees', 'INR', '₹');
